security:

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: 1234
                        roles: 'ROLE_ADMIN'
                    user:
                        password: 4321
                        roles: 'ROLE_USER'

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate
            logout_on_user_change: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/list, roles: [ ROLE_ADMIN, ROLE_USER ] }
        - { path: ^/student/edit, roles: [ ROLE_ADMIN ] }
        - { path: ^/student/novy, roles: [ ROLE_ADMIN ] }
        - { path: ^/student/, roles: [ ROLE_ADMIN, ROLE_USER ] }
        - { path: ^/students/, roles: [ ROLE_ADMIN ] }